name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version-file: ./go.mod
    - name: Test
      run: go test -race -v ./...

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version-file: ./go.mod
    - name: Build
      run: go build -v ./...

  docker-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jan5u/jakki:latest
